[package]
name = "hawser"
version = "0.1.0"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3.54"

[dependencies]
libc = { version = "0.2", default-features = false }

